services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: leaflab
      POSTGRES_PASSWORD: leaflab
      POSTGRES_DB: leaflab
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
